wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1651782599
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      4: 3.10.4
      5: 0.12.16
      8:
      - 1
      - 3
      - 5
